[package]
name = "random-pokemon-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
image = "0.25.3"
rand = "0.8.5"
reqwest = "0.12.8"
rustemon = "3.5.0"
thiserror = "1.0.64"
tokio = { version = "1.40.0", features = ["full"] }
viuer = "0.8.1"
