[package]
name = "random-pokemon-generator"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = "0.28.1"
image = "0.25.5"
rand = "0.8.5"
reqwest = "0.12.8"
rustemon = "4.0.0"
thiserror = "2.0.6"
tokio = { version = "1.42.0", features = ["full"] }
viuer = "0.9.1"
